# Generated by Django 3.2.5 on 2021-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pilot_name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
    ]
