# Generated by Django 3.2.5 on 2021-07-24 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_entry_pilot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='from_dest',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='[A-Z][A-Z][A-Z][A-Z]')]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='to_dest',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='[A-Z][A-Z][A-Z][A-Z]')]),
        ),
    ]
