# Generated by Django 3.2.5 on 2021-07-25 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20210724_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='aircraft_icao',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(regex='[0-9A-Z][0-9A-Z][0-9A-Z][0-9A-Z]')]),
        ),
    ]
