# Generated by Django 3.2.5 on 2021-07-25 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_entry_aircraft_icao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='aircraft_icao',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(regex='[0-9A-Z]{0-4}}')]),
        ),
    ]
