# Generated by Django 3.2.5 on 2021-07-25 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_alter_entry_aircraft_icao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='aircraft_id_num',
            new_name='aircraft_reg',
        ),
        migrations.AddField(
            model_name='entry',
            name='airline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^([A-Za-z]{3}|[A-Za-z][0-9]|[0-9][A-Za-z])([0-9]+)$')]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='aircraft_icao',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(regex='/^[A-Z]{1}[A-Z0-9]{1,3}$/')]),
        ),
    ]
