# Generated by Django 3.2.5 on 2021-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_alter_entry_aircraft_icao'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pilot_identifier',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
